module.exports = {
    channelCreate: require('./Functions/Channel/Create'),
    channelDelete: require('./Functions/Channel/Delete'),
    channelUpdate: require('./Functions/Channel/Update'),
    channelOverwriteCreate: require('./Functions/ChannelOverwrite/Create'),
    channelOverwriteDelete: require('./Functions/ChannelOverwrite/Delete'),
    channelOverwriteUpdate: require('./Functions/ChannelOverwrite/Update'),
    emojiCreate: require('./Functions/Emoji/Create'),
    emojiDelete: require('./Functions/Emoji/Delete'),
    emojiUpdate: require('./Functions/Emoji/Update'),
    roleCreate: require('./Functions/Role/Create'),
    roleDelete: require('./Functions/Role/Delete'),
    roleUpdate: require('./Functions/Role/Update'),
    stickerCreate: require('./Functions/Sticker/Create'),
    stickerDelete: require('./Functions/Sticker/Delete'),
    stickerUpdate: require('./Functions/Sticker/Update'),
    webhookCreate: require('./Functions/Webhook/Create'),
    webhookDelete: require('./Functions/Webhook/Delete'),
    webhookUpdate: require('./Functions/Webhook/Update'),
    memberBan: require('./Functions/Member/Ban'),
    memberUnban: require('./Functions/Member/Unban'),
    memberKick: require('./Functions/Member/Kick'),
    memberRoleUpdate: require('./Functions/Member/RoleUpdate'),
    memberUpdate: require('./Functions/Member/Update'),
    botAdd: require('./Functions/Guild/Bot'),
    guildUpdate: require('./Functions/Guild/Update'),
}